const COMMAND_TYPES = Object.freeze({
  PING: "PING",
  CAMERA_ON: "CAMERA_ON",
  CAMERA_OFF: "CAMERA_OFF",
  CAPTURE_IMAGE: "CAPTURE_IMAGE",
  HIGH_POWER_TRANSMISSION: "HIGH_POWER_TRANSMISSION",
  HEATER_ON: "HEATER_ON",
  HEATER_OFF: "HEATER_OFF",
  CHANGE_ORIENTATION: "CHANGE_ORIENTATION",
  ENTER_SAFE_MODE: "ENTER_SAFE_MODE",
  RECOVER: "RECOVER",
});

module.exports = { COMMAND_TYPES };